/* Provenance of the shipped reference data. Generated by tools/build-reference.mjs. */
FCT.DATA.info = {
    "source": "the-fab-cube/flesh-and-blood-cards",
    "branch": "develop",
    "commit": "18b2d9d74e2f57a025bb62820bf35a13477a895b",
    "commitDate": "2026-09-30",
    "built": "2026-09-30"
};
