/* Provenance of the shipped reference data. Generated by tools/build-reference.mjs. */
FCT.DATA.info = {
    "source": "the-fab-cube/flesh-and-blood-cards",
    "branch": "develop",
    "commit": "e56071b41b6e784b652eeada1ff86e6d8538f554",
    "commitDate": "2026-08-21",
    "built": "2026-09-25",
    "fabraryHeader": [
        "Identifier",
        "Name",
        "Pitch",
        "Set",
        "Set number",
        "Edition",
        "Foiling",
        "Treatment",
        "Have",
        "Want in trade",
        "Want to buy",
        "Extra for trade",
        "Extra to sell"
    ]
};
